---
title: "test_spark_h2o"
author: "Arie Twigt"
date: "4-10-2018"
output: html_document
---

```{r}
library(dplyr)
library(sparklyr)
```

```{r}
#options(rsparkling.sparklingwater.version = "2.1.14")
```


```{r}
config = spark_config()
config$`sparklyr.shell.driver-memory` <- "6G"
config$`sparklyr.shell.executor-memory` <- "6G"
config$`spark.yarn.executor.memoryOverhead` <- "2G"
```

```{r}
sc <- spark_connect("local", 
                    version = "2.1.0",
                    config = config)
```

```{r}
start <- Sys.time()

spark_read_csv(sc, 
               name = "alleen_personenauto", 
               path = "data/alleen_personenauto.csv")

end <- Sys.time()
```

Check tables in spark

```{r}
src_tbls(sc)
```

Read into R

```{r}
tbl_autos <- tbl(sc, "alleen_personenauto")
```

Spark is Lazy

```{r}
audis <- tbl_autos %>%
  filter(Merk == "AUDI")
```


```{r}
class(audis)
```

```{r}
head(audis)
```

Execute Spark 

```{r}
audis_df <- collect(audis)
```


Create RDD based on other RDD

```{r}
audis_stations_df <- audis_df %>%
  filter(Inrichting == "stationwagen")
```


# Basic Machine Learning

Check available features

```{r}
str(audis_stations_df)
```

```{r}
audis_clean <- audis %>%
  mutate(Catalogusprijs = regexp_replace(Catalogusprijs, ",", ".")) %>% # regex
  mutate(Catalogusprijs = as.numeric(Catalogusprijs)) %>% # convert columns
  select(Catalogusprijs, Aantal_cilinders) %>% # select columns
  na.omit() # remove rows with empty values ('NA', 'NaN' etc.)
```

# predict price per cilinder

```{r}
lm_model_1 <- audis_clean %>%
  ml_linear_regression(Catalogusprijs ~ Aantal_cilinders) 
```

Show model performance

```{r}
summary(lm_model_1)
```


New model, importing cars cheaper?

```{r}
audis_clean <- audis %>%
  mutate(Catalogusprijs = regexp_replace(Catalogusprijs, ",", ".")) %>% # regex
  mutate(Catalogusprijs = as.numeric(Catalogusprijs)) %>% # convert columns
  select(Catalogusprijs, Aantal_cilinders, Export_indicator) %>% # select columns
  na.omit() # remove rows with empty values ('NA', 'NaN' etc.)

```

# predict price per cilinder added with export indicator

```{r}
lm_model_2 <- audis_clean %>%
  ml_linear_regression(Catalogusprijs ~ Aantal_cilinders + Export_indicator) 
```

Show model performance

```{r}
summary(lm_model_2)
```

